<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>CGE_MouseControll</RootNamespace>
    <AssemblyName>CGE_MouseControll</AssemblyName>
    <AssemblyTitle>CGE_MouseControll</AssemblyTitle>
    <Product>CGE_MouseControll</Product>
    <Copyright>Copyright ©  2024</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ConsoleGameEngine\ConsoleGameEngine.csproj" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>