<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyTitle>CGE_Animation</AssemblyTitle>
    <Company>Diehl Informatik GmbH</Company>
    <Product>CGE_Animation</Product>
    <Copyright>Copyright © Diehl Informatik GmbH 2024</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ConsoleGameEngine\ConsoleGameEngine.csproj" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>